// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6dQPmcMKAP7gHYtiTquSma_msosfqk1k',
    appId: '1:123423309183:web:c99c6efba6ffbe8229ae4a',
    messagingSenderId: '123423309183',
    projectId: 'phlipkart-689dc',
    authDomain: 'phlipkart-689dc.firebaseapp.com',
    storageBucket: 'phlipkart-689dc.appspot.com',
    measurementId: 'G-GZJJLZTLXB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4MlRNpsSIeKxvlQ3uJIZuoIYiVXicdE0',
    appId: '1:123423309183:android:a89150238bb6f02929ae4a',
    messagingSenderId: '123423309183',
    projectId: 'phlipkart-689dc',
    storageBucket: 'phlipkart-689dc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCU6p0BXjfYNAmArfNY1tzT9qC9CkcNPKk',
    appId: '1:123423309183:ios:9e1eaca6eb79016629ae4a',
    messagingSenderId: '123423309183',
    projectId: 'phlipkart-689dc',
    storageBucket: 'phlipkart-689dc.appspot.com',
    androidClientId: '123423309183-o8pgq2jbkfjk561uekigk0hk8a77t08g.apps.googleusercontent.com',
    iosClientId: '123423309183-naqee2n9js57177j8nrsmre1kqjj7sou.apps.googleusercontent.com',
    iosBundleId: 'com.example.fluttersubject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCU6p0BXjfYNAmArfNY1tzT9qC9CkcNPKk',
    appId: '1:123423309183:ios:9e1eaca6eb79016629ae4a',
    messagingSenderId: '123423309183',
    projectId: 'phlipkart-689dc',
    storageBucket: 'phlipkart-689dc.appspot.com',
    androidClientId: '123423309183-o8pgq2jbkfjk561uekigk0hk8a77t08g.apps.googleusercontent.com',
    iosClientId: '123423309183-naqee2n9js57177j8nrsmre1kqjj7sou.apps.googleusercontent.com',
    iosBundleId: 'com.example.fluttersubject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6dQPmcMKAP7gHYtiTquSma_msosfqk1k',
    appId: '1:123423309183:web:a4bef261bfb749c029ae4a',
    messagingSenderId: '123423309183',
    projectId: 'phlipkart-689dc',
    authDomain: 'phlipkart-689dc.firebaseapp.com',
    storageBucket: 'phlipkart-689dc.appspot.com',
    measurementId: 'G-R7EM7X7F25',
  );
}
